### ISSUE TITLE
only ios will build faliure

### ISSUE THREAD

**Issue by bau720123** [performanceactive/phonegap-custom-camera-plugin#1]
hi @performanceactive 
I am using pgb 3.3
and only ios will build faliure
https://build.phonegap.com/plugins/668

**Comment by cvanes** [comment]
Do you have any more information? Build logs, error messages etc.

**Comment by bau720123** [comment]
hi @cvanes 
it will appear this wrong message (only in ios)
http://www.littlebau.com/cam.gif

by the way...
my dreamweaver cc wrong message
SyntaxError: JSON.parse

**Comment by cvanes** [comment]
Based on the image above, how do you know that the plugin is the cause and not your app?

Also, JSON.parse is not used by the plugin, it may be used by the phonegap/cordova scripts but not by the plugin directly.

**Comment by bau720123** [comment]
hi @cvanes 
I am just only use PGB (build.phonegap.com)
when I add only this plugin，the ios will build fail
otherwise...it will success
you can try by yourself that you will know what I am talking about

**Comment by cvanes** [comment]
We also use build.phonegap.com and phonegap 3.3 with no issues. 

Did Adobe respond with any information when you notified them of the issue?

**Comment by bau720123** [comment]
hi @cvanes 
so strange...
anyway...I will try looking for the answer by PGB team
http://community.phonegap.com/nitobi/topics/only_ios_will_build_faliure?rfm=1
if anything update，I will inform you

**Comment by bau720123** [comment]
now I am using PGB 3.4 with latest plugin 1.3 
https://build.phonegap.com/plugins/703 
but still have trouble 
only ios will build faliure but others (Android and winphone) are build fine
http://community.phonegap.com/nitobi/topics/only_ios_will_build_faliure?rfm=1
still waiting response~

**Comment by cvanes** [comment]
Without any information to debug, it's difficult to know where the issue lies. 

One other thing to note is that the plugin doesn't support Windows Phone, it's iOS and Android only.

**Comment by bau720123** [comment]
hi @cvanes 
find the solution
it's my fault，sorry

in my config.xml 
I have a lot of html's Comment 
such like this =>  
But I ended up in some places just like this =>  
so...it will cause the ios build error too
share this note to you

I will close this article by myself
